# my_config.yaml


##########################################################################################

# LOGGING
logging:
  file_level: DEBUG
  console_level: DEBUG

##########################################################################################

# PATHS


##########################################################################################
