# Generated by Django 5.0.3 on 2024-03-14 05:33
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoFetchTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('datetime', models.DateTimeField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('bid', models.FloatField()),
                ('bidVolume', models.FloatField()),
                ('ask', models.FloatField()),
                ('askVolume', models.FloatField()),
                ('vwap', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('last', models.FloatField()),
                ('previousClose', models.FloatField()),
                ('change', models.FloatField()),
                ('percentage', models.FloatField()),
                ('average', models.FloatField()),
                ('baseVolume', models.FloatField()),
                ('quoteVolume', models.FloatField()),
                ('info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CryptoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
