# Generated by Django 5.0.3 on 2024-03-15 11:03
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('close', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='CryptoFetchTicker',
        ),
        migrations.DeleteModel(
            name='CryptoOrder',
        ),
        migrations.DeleteModel(
            name='CryptoTrades',
        ),
    ]
