# Generated by Django 5.0.3 on 2024-03-21 13:01
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cryptoprice_delete_cryptofetchticker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoPrice',
        ),
    ]
